name: Sync Image
description: 同步一个镜像 (需要 Image 已在白名单里)
labels:
- sync image
body:
- type: markdown
  attributes:
    value: |
      # ↑↑↑↑↑↑↑↑↑↑↑ 填入你要同步的 Image
      ## 请包含 域名/路径:标签

- type: markdown
  attributes:
    value: |
      ## 也可以调用接口触发, 集成进 CI
      ``` bash
      curl -X POST \
        -H "Authorization: Bearer ${TOKEN}" \
        -H "Accept: application/vnd.github+json" \
        https://api.github.com/repos/DaoCloud/public-image-mirror/issues \
        -d "{
          \"title\": \"${IMAGE}\",
          \"labels\": [\"sync image\"],
          \"template\": \"sync-image\"
      }"
      ```

- type: checkboxes
  attributes:
    label: 镜像域名 (镜像仓库)
    options:
    - label: 请确保包含域名(domain)
- type: markdown
  attributes:
    value: |
      - 如 docker.io/
      - 如 registry.k8s.io/
      - 如果不包含域名, 需要主动添加默认的 docker.io/

- type: checkboxes
  attributes:
    label: 镜像标签
    options:
    - label: 请确保包含镜像的标签(tag)
- type: markdown
  attributes:
    value: |
      - 如 :latest
      - 如 :v1

- type: checkboxes
  attributes:
    label: 镜像存在
    options:
    - label: 请确保这个镜像真实存在
- type: markdown
  attributes:
    value: |
      - 如 docker.io/library/busybox:latest
      - 如 docker.io/kindest/node:v1.30.0
      - 如 registry.k8s.io/kubectl:v1.30.0

- type: markdown
  attributes:
    value: |
      有疑问反馈, 请添加我们的企微群 [#4183](https://github.com/DaoCloud/public-image-mirror/issues/4183)
