name: "Check Image"
on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        run: |
          ./scripts/check-image.sh
