name: "Check"
on:
  workflow_dispatch:

  schedule:
    - cron: "0 20 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check
        env:
          INCREMENTAL: "true"
          QUICKLY: "true"
          PARALLET: "10"
        run: |
          ./hack/diff.sh
      - name: Update badge
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Generated for update gist
          BADGE_PREFIX: "gist://wzshiming/6e1f67a5184f93cefc5b2c670a5813e5"
          QUICKLY: "true"  
        run: |
          wget https://github.com/wzshiming/putingh/releases/download/v0.6.3/putingh_linux_amd64 -O /usr/local/bin/putingh && chmod +x /usr/local/bin/putingh
          ./hack/badge.sh
          GH_TOKEN="${GH_TOKEN}" putingh "${BADGE_PREFIX}/daocloud-sync-badge.svg" badge.svg
          GH_TOKEN="${GH_TOKEN}" putingh "${BADGE_PREFIX}/daocloud-sync.log" sync.log
