name: "Check Image"
on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip3 install yq
      - name: Check
        env:
          INCREMENTAL: "true"
          DEBUG: "true"
          QUICKLY: "true"
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/check-image.sh
