name: "Deep Sync Check"
on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

jobs:
  deep-sync-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip3 install yq
      - name: Check
        env:
          INCREMENTAL: "true"
          DEBUG: "true"
          QUICKLY: ""
        run: |
          ./scripts/check-image.sh
      - name: Update badge
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Generated for update gist
          BADGE_PATH: "gist://wzshiming/6e1f67a5184f93cefc5b2c670a5813e5/daocloud-deep-sync-badge.svg"
        run: |
          wget https://github.com/wzshiming/putingh/releases/download/v0.6.2/putingh_linux_amd64 -O /usr/local/bin/putingh && chmod +x /usr/local/bin/putingh
          GH_TOKEN="${GH_TOKEN}" putingh "${BADGE_PATH}" sync.svg
