name: Verify Format

on:
  pull_request:
    branches: [main]

jobs:
  Patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify domain.txt
        run: |
          ./hack/verify-fmt.sh domain.txt || { echo "Please run './hack/fmt.sh domain.txt'"; exit 1; }
      - name: Verify mirror.txt
        run: |
          ./hack/verify-fmt.sh mirror.txt || { echo "Please run './hack/fmt.sh mirror.txt'"; exit 1; }
